### ISSUE TITLE
activity filters not working in firefox

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-dashboard#11]
Clicking on "Access Document", "Save" etc under actions table https://transkribus.eu/readTest/dashboard/ results in transkribus comms error. Happens in firefox, fine in chrome.

**Comment by maxbry** [comment]
Currently, you click on one filter and that gets active. To release a filter, you have to click on X. What about being able to activate more than one filter and releasing them by clicking on them again?
