### ISSUE TITLE
"Activities for..." drop down not populated for some collections

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-dashboard#12]
eg https://transkribus.eu/readTest/dashboard/4

There may be a good reason (possibly due to role?)

**Comment by cziaarm** [comment]
Actually thinking about this... The above example (for a transcriber user) is probably the correct behaviour (or something close). Another collection for which I am a Transcriber *does* show all the other users and their email addresses, which is probably a less good idea. I can check and suppress this behaviour, but (@kahlep) maybe worth examining whether it is something that the transkribus api should be allowing?

**Comment by maxbry** [comment]
When looking in `collection.html`, there should be one `<li>` element:

    <a href="#" data-toggle="dropdown">{% trans 'Activities for... ' %}<span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu" id="user_list">
        <li><a href="#user_list_panel" data-toggle="tab">{% trans 'Default 4' %}</a></li>
    </ul>

But in the generated html there is none..

**Comment by cziaarm** [comment]
@maxbry I agree. Though the question of whether Transcribers should be seeing this list at all still stands.
