### ISSUE TITLE
Data table paging of activities in firefox causes error

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-dashboard#13]
File "/home/cziaarm/READ/mc/apps/utils/views.py", line 130, in table_ajax
    (data,count) = paged_data(request,t_list_name,params)
ValueError: need more than 1 value to unpack

**Comment by cziaarm** [comment]
In document view (eg http://127.0.0.1:8003/dashboard/619/443)
There is a precursor to the above error which suggests that the paging is not sendding a valid number  as the "start" param

File "/home/cziaarm/READ/mc/apps/utils/views.py", line 364, in paged_data
    params['index'] = int(dt_params.get('start')) if dt_params.get('start') else 0
ValueError: invalid literal for int() with base 10: 'NaN'

**Comment by maxbry** [comment]
(data,count) = paged_data(request,t_list_name,params)
In some case, probably always when using the pagination, the returned object is not a tuple but an object of type django.http.HttpResponse

**Comment by cziaarm** [comment]
@maxbry That could be a symptom of the not-so-clever handling of errors from transkribus requests. Transkribus/TWI-utils#5

**Comment by maxbry** [comment]
Further investigation show that the triggered request in the background leads to a 404:
    https://transkribus.eu/TrpServer/rest/actions/list?end=1495634033737&start=NaN&index=5&nValues=5
Is this caused by the NaN?

**Comment by cziaarm** [comment]
I would say so.


and that NaN will be caused by the firefox bug with the start date, so fix that and...


?


Rory McNicholl
Lead developer
Digital Archives & Research Technologies
University of London Computer Centre
Senate House
Malet Street
London
WC1E 7HU

t: +44 (0)20 7863 1344
e: rory.mcnicholl@london.ac.uk
w: http://www.ulcc.ac.uk/

The University of London is an exempt charity in England and Wales.
________________________________

**Comment by maxbry** [comment]
Possible. So let's first fix the start date bug and then we'll see if the other problem is solved as well.
