### ISSUE TITLE
Identical rows in 'My recent document accesses'

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TWI-dashboard#14]
They should be omitted. Is there a rest service needed where we get the page nr as well for each action? Or we show the pageID which is stored in the action?

**Comment by cziaarm** [comment]
When the action type is "login" there is no page document or collection associated with it and for "document access" there is no page, only document and collection. This plus the fact that the actions are displayed "to the minute" means that it may give the impression of duplicate rows when there actually two document accesses within a minute.

**Comment by cziaarm** [comment]
That said Transkribus/TWI-dashboard#15

**Comment by cziaarm** [comment]
close with Transkribus/TWI-dashboard#15  9663689
