### ISSUE TITLE
Click on bar in most active collections chart misses directory context

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-dashboard#2]
https://github.com/Transkribus/TWI-mc/blob/9e3f8db3ef1289a81626ef9573549e7d3a203de0/static/js/read.js#L441-L466

use make_url (and decide between serverbase or appbase in make_url) appbase used currently but this serverbase was appropriate in some situations. audit these urls with and with out use of subdirectory to find robust solution...

**Comment by jnphilipp** [comment]
Is still there.
