### ISSUE TITLE
Users table: Can't sort user table by username

### ISSUE THREAD

**Issue by cziaarm** [Transkribus/TWI-dashboard#20]
https://transkribus.eu/readTest/dashboard/2305

**Comment by maxbry** [comment]
`apps/utils/static/js/read.js:79` <- does this line has anything to do with the mentioned bug?

**Comment by cziaarm** [comment]
yes looks like the first column (and in theory the last) are non-sortable by default (or default as defined in init_datatables

I can't remember the reasoning behind this...  @hackmanschorsch  Is that something you have added? I wonder if the same thing could be achieved in a more targeted way by setting that option in the columns that are passed into init_datatables where necessary?

https://datatables.net/reference/option/columns

**Comment by hackmanschorsch** [comment]
Oh yes. This stems from the fact that we all share the same datatable and for myCollections e.g. the first column are the thumbs where sorting makes no sense. So I think your suggestion would be nice to have.

**Comment by cziaarm** [comment]
have turned off the global setting of searchable and orderable in read,js and switched it on for the first column in the collections table in library.js

Transkribus/TWI-mc@384a616fc1f9cff5b00ff87ac30d2a4bf5667e77
