### ISSUE TITLE
Changing collection details description

### ISSUE THREAD

**Issue by maxbry** [Transkribus/TWI-dashboard#28]
Changes:
From:
    Collection TEST_Königsfelden_Kopialbücher with ID 5032 contains
    Documents: 10, Lines transcribed: 7361, Words transcribed: 44338
    Tags: Persons(115), ...

To:
    TEST_Königsfelden_Kopialbücher with ID 5032 contains
    10 Documents, 44.338 words
    Tags: 115 Persons, ...

**Comment by cziaarm** [comment]
@maxbry Can't find this to test.. I assume it is the way that collection stats are presented on the collections page. But there are no stats other than the number of docs currently...

**Comment by cziaarm** [comment]
I see now that this is the info at the top of the collection page.

More stats will be available soon.

However I think that the need for the collection title has been superseded by it's presence in the breadcrumb.

**Comment by maxbry** [comment]
Probably duplicate of issue [#10](https://github.com/Transkribus/TWI-library/issues/10)
